# Generated by Django 3.1a1 on 2021-03-30 17:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50)),
                ('Date_posted', models.DateTimeField(default=datetime.datetime(2021, 3, 30, 17, 18, 38, 718779, tzinfo=utc))),
                ('Content', models.TextField()),
                ('Author', models.CharField(max_length=50)),
            ],
        ),
    ]
