# Generated by Django 3.1a1 on 2021-03-31 04:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Date_posted',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 31, 4, 59, 26, 225083, tzinfo=utc)),
        ),
    ]
